name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: go test -race -v ./...

  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Lint
      uses: golangci/golangci-lint-action@v2.3.0
